### ISSUE TITLE
memory leak found

### ISSUE THREAD

**Issue by 751620780** [Velocidex/oleparse#3]
My test code is as follows:
```go
package main

import (
	"fmt"
	_ "net/http/pprof"
	"os"
	"path/filepath"
	"runtime"

	"github.com/Velocidex/oleparse"
)

var data []byte = make([]byte, 50*1024*1024)

func walkFun(path string, info os.FileInfo, err error) error {
	if err != nil {
		return err
	}
	if info.IsDir() {
		return nil
	}
	size := int(info.Size())
	if size > 50*1024*1024 {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	n, err := f.Read(data)
	if n != size {
		fmt.Printf("%s read failed, pass\n", path)
		return nil
	}
	if err != nil {
		return nil
	}
	oleparse.NewOLEFile(data)
	return nil
}

func MemoryInfo() uint64 {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m.Sys
}

func main() {
	filepath.Walk(`D:\samples\bad_ole`, walkFun)
	fmt.Printf("memory size=%.2f MB \n", float64(MemoryInfo())/1024.0/1024.0)
}
```
When the file MD5 =**0ffe31cbb1480cc457f642ffe33e7cd9** is parsed, the process memory grows rapidly, resulting in program crash.
Sample files that cause code problems can be downloaded [here](https://github.com/Velocidex/oleparse/files/7174775/bad_ole.zip)

**Comment by scudette** [comment]
Thank you for reporting it and including the sample. This file seems to be truncated. With the latest commit we reject the file with an EOF. This seems to be the same behavior as oledir:
```
$ oledir 0ffe31cbb1480cc457f642ffe33e7cd9
oledir 0.54 - http://decalage.info/python/oletools
OLE directory entries in file /shared/malware/0ffe31cbb1480cc457f642ffe33e7cd9:
Traceback (most recent call last):
  File "/home/mic/Dev/bin/oledir", line 8, in <module>
    sys.exit(main())
  File "/home/mic/Dev/lib/python3.9/site-packages/oletools/oledir.py", line 179, in main
    ole = olefile.OleFileIO(filename)
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1348, in open
    self.loadfat(header)
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1515, in loadfat
    self.loadfat_sect(sect)
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1490, in loadfat_sect
    s = self.getsect(isect)
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1646, in getsect
    self._raise_defect(DEFECT_FATAL, 'incomplete OLE sector')
  File "/home/mic/Dev/lib/python3.9/site-packages/olefile/olefile.py", line 1105, in _raise_defect
    raise exception_type(message)
OSError: incomplete OLE sector
```

and oleparser
```
$ oleparse 0ffe31cbb1480cc457f642ffe33e7cd9
oleparse: error: Parsing: While parsing 0ffe31cbb1480cc457f642ffe33e7cd9: EOF
```
